---
# tasks file for CICDSystem

- name: Check for any existing CICDSystem CRs in the cluster - only one is allowed
  block:
    - name: Get the CICDSystem CRs
      kubernetes.core.k8s_info:
        api_version: cicd.kemo.dev/v1alpha1
        kind: CICDSystem
      register: cicd_system_info

    - name: Fail if more than one CICDSystem CR is found
      ansible.builtin.assert:
        that:
          - cicd_system_info.resources | length <= 1
        fail_msg: "Only one CICDSystem CR is allowed in the cluster"
        success_msg: "Only one CICDSystem CR is found in the cluster - proceeding with the deployment"

- name: Deployment of the OpenShift Pipelines Operator
  when: pipelines.deploy_openshift_pipelines
  include_tasks: openshift-pipelines-deployment.yml    

- name: Deploy the CD System
  when: cd.argocd.enabled or cd.rhacm.enabled
  block:
    - name: OpenShift GitOps Operator Deployment
      when: cd.argocd.deploy_operator
      include_tasks: openshift-gitops-deployment.yml

    - name: Red Hat Advanced Cluster Management Operator Deployment
      when: cd.rhacm.deploy_operator
      include_tasks: rhacm-operator-deployment.yml

- name: Integrate RHACM and OpenShift Gitops
  when: cd.rhacm.enabled and cd.argocd.enabled
  include_tasks: rhacm-gitops-integration.yml