---
# tasks file for CICDSystem

- name: Deployment of the OpenShift Pipelines Operator
  when: pipelines.deploy_openshift_pipelines
  include_tasks: openshift-pipelines-deployment.yml    

- name: Deploy the CD System
  when: cd.argocd.enabled or cd.rhacm.enabled
  block:
    - name: OpenShift GitOps Operator Deployment
      when: cd.argocd.deploy_operator
      include_tasks: openshift-gitops-deployment.yml

    - name: Red Hat Advanced Cluster Management Operator Deployment
      when: cd.rhacm.deploy_operator
      include_tasks: rhacm-operator-deployment.yml

- name: Integrate RHACM and OpenShift Gitops
  when: cd.rhacm.enabled and cd.argocd.enabled
  include_tasks: rhacm-gitops-integration.yml