---
- name: Check for the OpenShift Pipelines Subscription
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    namespace: openshift-operators
    name: openshift-pipelines-operator
  register: openshift_pipelines_subscription

- name: Deploy the OpenShift Pipelines Operator if it does not exist
  when: openshift_pipelines_subscription.resources | length == 0
  kubernetes.core.k8s:
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: openshift-pipelines-operator
        namespace: openshift-operators
        ownerReferences:
          - apiVersion: cicd.kemo.dev/v1alpha1
            kind: CICDSystem
            name: "{{ ansible_operator_meta.name }}"
            uid: "{{ ansible_operator_meta.uid }}"
      spec:
        channel: "{{ openshift_pipelines_channel }}"
        name: openshift-pipelines-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
    state: present

- name: Wait for the OpenShift Pipelines Operator to be ready
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: openshift-operators
    label_selectors:
      - "operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators="
  register: openshift_pipelines_csv
  until: openshift_pipelines_csv.resources | list | length > 0
  retries: 100
  delay: 10


- name: Create Pipelines Templates
  when: pipelines.create_templates
  block:
    - name: Ensure that the Tekton ClusterTasks CRD exists
      kubernetes.core.k8s_info:
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: clustertasks.tekton.dev
      register: tekton_ct_crd_check
      retries: 200
      delay: 10
      until: tekton_ct_crd_check.resources | list | length == 1

    - name: Create the Dockerfile creation ClusterTask
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'templates/dockerfile-creation-buildah-clustertask.yaml.j2') }}"