# permissions for end users to edit cicdsystems.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cicdsystem-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ansible-cicd-operator
    app.kubernetes.io/part-of: ansible-cicd-operator
    app.kubernetes.io/managed-by: kustomize
  name: cicdsystem-editor-role
rules:
- apiGroups:
  - cicd.kemo.dev
  resources:
  - cicdsystems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cicd.kemo.dev
  resources:
  - cicdsystems/status
  verbs:
  - get
