# permissions for end users to edit appdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cicd-operator-reader-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ansible-cicd-operator
    app.kubernetes.io/part-of: ansible-cicd-operator
    app.kubernetes.io/managed-by: kustomize
  name: cicd-operator-reader-role
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
      - operatorgroups
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - clustertasks
      - pipelines
      - pipelineruns
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - operator.open-cluster-management.io
    resources:
      - multiclusterhubs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - cluster.open-cluster-management.io
    resources:
      - managedclustersetbindings
      - placements
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - apps.open-cluster-management.io
    resources:
      - gitopsclusters
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - argoproj.io
    resources:
      - argocds
      - applications
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - patch