# permissions for end users to view gitrepoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gitrepo-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ansible-cicd-operator
    app.kubernetes.io/part-of: ansible-cicd-operator
    app.kubernetes.io/managed-by: kustomize
  name: gitrepo-viewer-role
rules:
- apiGroups:
  - cicd.kemo.dev
  resources:
  - gitrepoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cicd.kemo.dev
  resources:
  - gitrepoes/status
  verbs:
  - get
