apiVersion: cicd.kemo.dev/v1alpha1
kind: CICDSystem
metadata:
  labels:
    app.kubernetes.io/name: cicdsystem
    app.kubernetes.io/instance: cicdsystem-sample
    app.kubernetes.io/part-of: ansible-cicd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ansible-cicd-operator
  name: cicdsystem-sample
spec:
  # TODO(user): Add fields here
  pipelines:
    deploy_openshift_pipelines: true
    openshift_pipelines_channel: stable

  cd:
    rhacm:
      enabled: true
      deploy_operator: true
      rhacm_operator_channel: release-2.10
      operator_update_strategy: Automatic # Automatic or Manual
    argocd:
      enabled: true
      deploy_operator: true
      gitops_operator_channel: latest
      operator_update_strategy: Automatic # Automatic or Manual
    system_type: argocd # argocd or rhacm - this defines what kind of Application artifacts are created