apiVersion: cicd.kemo.dev/v1alpha1
kind: AppDeployment
metadata:
  labels:
    app.kubernetes.io/name: appdeployment
    app.kubernetes.io/instance: appdeployment-sample
    app.kubernetes.io/part-of: ansible-cicd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ansible-cicd-operator
  name: appdeployment-sample
spec:
  source:
    repoURL: https://github.com/kenmoini/ai-lab-recipes
    branch: main
    contextDir: convert_models
  registry:
    name: imageregistry-sample
  target:
    cluster: local-cluster
    namespace: convert-models