apiVersion: cicd.kemo.dev/v1alpha1
kind: GitRepo
metadata:
  labels:
    app.kubernetes.io/name: gitrepo
    app.kubernetes.io/instance: gitrepo-sample
    app.kubernetes.io/part-of: ansible-cicd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ansible-cicd-operator
  name: gitrepo-sample
spec:
  # TODO(user): Add fields here
  url: git@github.com:kenmoini/cicd-system-apps.git
  branch: deploy
  credentials:
    name: git-credentials
    namespace: cicd-system
