apiVersion: cicd.kemo.dev/v1alpha1
kind: CICDSystem
metadata:
  labels:
    app.kubernetes.io/name: cicdsystem
    app.kubernetes.io/instance: cicdsystem-sample
    app.kubernetes.io/part-of: ansible-cicd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ansible-cicd-operator
  name: cicdsystem-sample
spec:
  pipelines:
    deploy_openshift_pipelines: true
    openshift_pipelines_channel: stable
    create_templates: true

  cd:
    rhacm:
      enabled: true
      deploy_operator: true
      rhacm_operator_channel: release-2.10
      # operator_update_strategy - Automatic or Manual
      operator_update_strategy: Automatic
    argocd:
      enabled: true
      deploy_operator: true
      gitops_operator_channel: latest
      # operator_update_strategy - Automatic or Manual
      operator_update_strategy: Automatic
    # system_type: argocd or rhacm - this defines what kind of Application artifacts are created
    system_type: argocd