apiVersion: cicd.kemo.dev/v1alpha1
kind: CICDSystem
metadata:
  labels:
    app.kubernetes.io/name: cicdsystem
    app.kubernetes.io/instance: cicdsystem-sample
    app.kubernetes.io/part-of: ansible-cicd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ansible-cicd-operator
  name: cicdsystem-sample
spec:
  # TODO(user): Add fields here
  pipelines:
    deploy_openshift_pipelines: true
    openshift_pipelines_channel: stable

