---
- name: Deploy application - ArgoCD
  when: cicd_system_info.resources[0].spec.cd.system_type == "argocd"
  block:
    - name: Create the ArgoCD Repository Secret
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'argocd-repo-secret.yml.j2') }}"
        state: present

    - name: ArgoCD Application
      when: _cicd_kemo_dev_appdeployment_spec.target.cluster.name is defined
      block:
        - name: Create ArgoCD Application
          kubernetes.core.k8s:
            definition: "{{ lookup('template', 'argocd-application.yml.j2') }}"
            state: present

        - name: Get the status of the ArgoCD Application
          block:
            - name: Get ArgoCD Application
              kubernetes.core.k8s_info:
                api_version: argoproj.io/v1alpha1
                kind: Application
                namespace: openshift-gitops
                name: "{{ ansible_operator_meta.name }}"
              register: argocd_application_info
              #until: (argocd_application_info.resources[0].status.health.status == "Healthy") and (argocd_application_info.resources[0].status.sync.status == "Synced")
              until: (argocd_application_info.resources[0].status.health.status == "Healthy")
              retries: 30
              delay: 10

            - name: Submit a new status for the Deployment
              operator_sdk.util.k8s_status:
                api_version: cicd.kemo.dev/v1alpha1
                kind: AppDeployment
                name: "{{ ansible_operator_meta.name }}"
                namespace: "{{ ansible_operator_meta.namespace }}"
                conditions:
                - type: Deployed
                  status: "True"
                  reason: ApplicationDeployed
                  message: "The Application '{{ ansible_operator_meta.name }}' was deployed successfully"
                  lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"
          rescue:
            - name: Failed to deploy the Application
              operator_sdk.util.k8s_status:
                api_version: cicd.kemo.dev/v1alpha1
                kind: AppDeployment
                name: "{{ ansible_operator_meta.name }}"
                namespace: "{{ ansible_operator_meta.namespace }}"
                conditions:
                - type: Deployed
                  status: "False"
                  reason: ApplicationDeploymentFailed
                  message: "The Application '{{ ansible_operator_meta.name }}' failed to deploy"
                  lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"

            - ansible.builtin.fail:
                msg: "The Application '{{ ansible_operator_meta.name }}' failed to deploy"

    - name: ArgoCD ApplicationSet
      when: _cicd_kemo_dev_appdeployment_spec.target.cluster.labelSelector is defined
      block:
        - name: Create ArgoCD ApplicationSet
          kubernetes.core.k8s:
            definition: "{{ lookup('template', 'argocd-applicationset.yml.j2') }}"
            state: present

        - name: Status Check
          block:
            - name: Get the status of the ArgoCD ApplicationSet
              kubernetes.core.k8s_info:
                api_version: argoproj.io/v1alpha1
                kind: ApplicationSet
                namespace: openshift-gitops
                name: "{{ ansible_operator_meta.name }}-appset"
                wait_condition:
                  status: "True"
                  type: ResourcesUpToDate
                  reason: ApplicationSetUpToDate
              register: argocd_applicationset_info

            - name: Submit a new status for the Deployment
              operator_sdk.util.k8s_status:
                api_version: cicd.kemo.dev/v1alpha1
                kind: AppDeployment
                name: "{{ ansible_operator_meta.name }}"
                namespace: "{{ ansible_operator_meta.namespace }}"
                conditions:
                - type: Deployed
                  status: "True"
                  reason: ApplicationSetDeployed
                  message: "The ApplicationSet '{{ ansible_operator_meta.name }}-appset' was deployed successfully"
                  lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"

          rescue:
            - name: Failed to deploy the ApplicationSet
              operator_sdk.util.k8s_status:
                api_version: cicd.kemo.dev/v1alpha1
                kind: AppDeployment
                name: "{{ ansible_operator_meta.name }}"
                namespace: "{{ ansible_operator_meta.namespace }}"
                conditions:
                - type: Deployed
                  status: "False"
                  reason: ApplicationSetDeploymentFailed
                  message: "The ApplicationSet '{{ ansible_operator_meta.name }}-appset' failed to deploy"
                  lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"

            - ansible.builtin.fail:
                msg: "The ApplicationSet '{{ ansible_operator_meta.name }}-appset' failed to deploy"

