---
# tasks file for AppDeployment
- name: Run preflight checks
  include_tasks: preflight.yml

- name: Get resources
  include_tasks: get_resources.yml

- name: Create and run the Tekton Pipeline
  include_tasks: pipeline.yml
