---
- name: Pipelines for Dockerbuild strategy
  when: _cicd_kemo_dev_appdeployment_spec.build.strategy == "docker"
  block:
    - name: Create the Pipeline for a Dockerfile build
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'dockerfile-creation-pipeline.yaml.j2') }}"
        state: present

    - name: Create the PipelineRun for a Dockerfile build
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'dockerfile-creation-pipelinerun.yaml.j2') }}"
        state: present
      register: created_pipelinerun

    - name: Submit a Pipeline Running Status
      operator_sdk.util.k8s_status:
        api_version: cicd.kemo.dev/v1alpha1
        kind: AppDeployment
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        conditions:
        - type: PipelineFinished
          status: "False"
          reason: PipelineRunning
          message: "The PipelineRun {{ created_pipelinerun.result.metadata.name }} for the AppDeployment is running"
          lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"

    - name: PipelineRun Watcher
      block:
        - name: Wait for the PipelineRun to finish
          kubernetes.core.k8s_info:
            kind: PipelineRun
            namespace: "{{ ansible_operator_meta.namespace }}"
            name: "{{ created_pipelinerun.result.metadata.name }}"
          register: pipelinerun_info
          until: pipelinerun_info.resources[0].status.completionTime is defined
          retries: 200
          delay: 30

        - name: Update the PipelineRun status if successful
          when: pipelinerun_info.resources[0].status.conditions[0].status == "True"
          operator_sdk.util.k8s_status:
            api_version: cicd.kemo.dev/v1alpha1
            kind: AppDeployment
            name: "{{ ansible_operator_meta.name }}"
            namespace: "{{ ansible_operator_meta.namespace }}"
            conditions:
            - type: PipelineFinished
              status: "True"
              reason: Successful
              message: "The PipelineRun {{ created_pipelinerun.result.metadata.name }} for the AppDeployment has succeeded"
              lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"

        - name: Update the PipelineRun status if it failed
          when: pipelinerun_info.resources[0].status.conditions[0].status == "False"
          operator_sdk.util.k8s_status:
            api_version: cicd.kemo.dev/v1alpha1
            kind: AppDeployment
            name: "{{ ansible_operator_meta.name }}"
            namespace: "{{ ansible_operator_meta.namespace }}"
            conditions:
            - type: PipelineFinished
              status: "False"
              reason: Failed
              message: "The PipelineRun {{ created_pipelinerun.result.metadata.name }} for the AppDeployment has succeeded"
              lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"

      rescue:
        - name: PipelineRun Watcher Failed
          operator_sdk.util.k8s_status:
            api_version: cicd.kemo.dev/v1alpha1
            kind: AppDeployment
            name: "{{ ansible_operator_meta.name }}"
            namespace: "{{ ansible_operator_meta.namespace }}"
            conditions:
            - type: PipelineFinished
              status: "False"
              reason: TimedOut
              message: "The PipelineRun {{ created_pipelinerun.result.metadata.name }} for the AppDeployment has timed out or an unknown error has occured."
              lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"
        - ansible.builtin.fail:
            msg: "The PipelineRun {{ created_pipelinerun.result.metadata.name }} for the AppDeployment has timed out or an unknown error has occured."