---

- name: Check for all the needed inputs
  block:
  - name: Ensure that all the needed variables are defined
    ansible.builtin.assert:
      that:
        - _cicd_kemo_dev_appdeployment_spec.sourceRepository is defined
        - _cicd_kemo_dev_appdeployment_spec.sourceRepository.contextDir is defined
        - _cicd_kemo_dev_appdeployment_spec.sourceRepository.gitRepo is defined
        - _cicd_kemo_dev_appdeployment_spec.sourceRepository.gitRepo.name is defined
        - _cicd_kemo_dev_appdeployment_spec.sourceRepository.gitRepo.namespace is defined
        - _cicd_kemo_dev_appdeployment_spec.registry is defined
        - _cicd_kemo_dev_appdeployment_spec.registry.name is defined
        - _cicd_kemo_dev_appdeployment_spec.registry.namespace is defined
        - _cicd_kemo_dev_appdeployment_spec.build is defined
        - _cicd_kemo_dev_appdeployment_spec.build.strategy is defined
        - _cicd_kemo_dev_appdeployment_spec.build.deployment_type is defined
        - _cicd_kemo_dev_appdeployment_spec.create_networking is defined
        - _cicd_kemo_dev_appdeployment_spec.create_networking.service is defined
        - _cicd_kemo_dev_appdeployment_spec.create_networking.route is defined
        - _cicd_kemo_dev_appdeployment_spec.create_networking.hostname is defined
        - _cicd_kemo_dev_appdeployment_spec.target is defined
        - _cicd_kemo_dev_appdeployment_spec.target.gitRepo is defined
        - _cicd_kemo_dev_appdeployment_spec.target.gitRepo.name is defined
        - _cicd_kemo_dev_appdeployment_spec.target.gitRepo.namespace is defined
      fail_msg: |
        One or more of the required variables are not defined:
        {{- ' sourceRepository' if not _cicd_kemo_dev_appdeployment_spec.sourceRepository is defined else '' }}
        {{- ' sourceRepository.contextDir' if not _cicd_kemo_dev_appdeployment_spec.sourceRepository.contextDir is defined else '' }}
        {{- ' sourceRepository.gitRepo' if not _cicd_kemo_dev_appdeployment_spec.sourceRepository.gitRepo is defined else '' }}
        {{- ' sourceRepository.gitRepo.name' if not _cicd_kemo_dev_appdeployment_spec.sourceRepository.gitRepo.name is defined else '' }}
        {{- ' sourceRepository.gitRepo.namespace' if not _cicd_kemo_dev_appdeployment_spec.sourceRepository.gitRepo.namespace is defined else '' }}
        {{- ' registry' if not _cicd_kemo_dev_appdeployment_spec.registry is defined else '' }}
        {{- ' registry.name' if not _cicd_kemo_dev_appdeployment_spec.registry.name is defined else '' }}
        {{- ' registry.namespace' if not _cicd_kemo_dev_appdeployment_spec.registry.namespace is defined else '' }}
        {{- ' build' if not _cicd_kemo_dev_appdeployment_spec.build is defined else '' }}
        {{- ' build.strategy' if not _cicd_kemo_dev_appdeployment_spec.build.strategy is defined else '' }}
        {{- ' build.deployment_type' if not _cicd_kemo_dev_appdeployment_spec.build.deployment_type is defined else '' }}
        {{- ' create_networking' if not _cicd_kemo_dev_appdeployment_spec.create_networking is defined else '' }}
        {{- ' create_networking.service' if not _cicd_kemo_dev_appdeployment_spec.create_networking.service is defined else '' }}
        {{- ' create_networking.route' if not _cicd_kemo_dev_appdeployment_spec.create_networking.route is defined else '' }}
        {{- ' create_networking.hostname' if not _cicd_kemo_dev_appdeployment_spec.create_networking.hostname is defined else '' }}
        {{- ' target' if not _cicd_kemo_dev_appdeployment_spec.target is defined else '' }}
        {{- ' target.gitRepo' if not _cicd_kemo_dev_appdeployment_spec.target.gitRepo is defined else '' }}
        {{- ' target.gitRepo.name' if not _cicd_kemo_dev_appdeployment_spec.target.gitRepo.name is defined else '' }}
        {{- ' target.gitRepo.namespace' if not _cicd_kemo_dev_appdeployment_spec.target.gitRepo.namespace is defined else '' }}
      success_msg: "All the required variables are defined"

- name: Check for the Source GitRepo CR
  block:
    - name: Get the specified Source GitRepo CR
      kubernetes.core.k8s_info:
        api_version: cicd.kemo.dev/v1alpha1
        kind: GitRepo
        name: "{{ _cicd_kemo_dev_appdeployment_spec.sourceRepository.gitRepo.name }}"
        namespace: "{{ _cicd_kemo_dev_appdeployment_spec.sourceRepository.gitRepo.namespace }}"
      register: source_gitrepo_info

    - name: Fail if the Source GitRepo CR is not found
      ansible.builtin.assert:
        that:
          - source_gitrepo_info.resources | length > 0
        fail_msg: "The specified Source GitRepo CR with the name {{ _cicd_kemo_dev_appdeployment_spec.sourceRepository.gitRepo.name }} is not found in the namepsace {{ _cicd_kemo_dev_appdeployment_spec.sourceRepository.gitRepo.namespace }}"
        success_msg: "The specified Source GitRepo CR is found in the cluster - proceeding with the deployment"

  rescue:
    - name: Failed to find the Source GitRepo CR
      operator_sdk.util.k8s_status:
        api_version: cicd.kemo.dev/v1alpha1
        kind: AppDeployment
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        conditions:
        - type: SourceGitRepoAvailable
          status: "False"
          reason: SourceGitRepoNotFound
          message: "The specified Source GitRepo CR with the name {{ _cicd_kemo_dev_appdeployment_spec.sourceRepository.gitRepo.name }} is not found in the namepsace {{ _cicd_kemo_dev_appdeployment_spec.sourceRepository.gitRepo.namespace }}"
          lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"
    - ansible.builtin.fail:
        msg: "The specified Source GitRepo CR with the name {{ _cicd_kemo_dev_appdeployment_spec.sourceRepository.gitRepo.name }} is not found in the namepsace {{ _cicd_kemo_dev_appdeployment_spec.sourceRepository.gitRepo.namespace }}"

- name: Pass a successful status if the Source GitRepo CR is found
  operator_sdk.util.k8s_status:
    api_version: cicd.kemo.dev/v1alpha1
    kind: AppDeployment
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    conditions:
    - type: SourceGitRepoAvailable
      status: "True"
      reason: SourceGitRepoFound
      message: "The specified Source GitRepo CR with the name {{ _cicd_kemo_dev_appdeployment_spec.sourceRepository.gitRepo.name }} is found in the namepsace {{ _cicd_kemo_dev_appdeployment_spec.sourceRepository.gitRepo.namespace }}"
      lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"

- name: Check for the Image Registry CR
  block:
    - name: Get the specified Image Registry CR
      kubernetes.core.k8s_info:
        api_version: cicd.kemo.dev/v1alpha1
        kind: ImageRegistry
        name: "{{ _cicd_kemo_dev_appdeployment_spec.registry.name }}"
        namespace: "{{ _cicd_kemo_dev_appdeployment_spec.registry.namespace }}"
      register: image_registry_info

    - name: Fail if the Image Registry CR is not found
      ansible.builtin.assert:
        that:
          - image_registry_info.resources | length > 0
        fail_msg: "The specified Image Registry CR with the name {{ _cicd_kemo_dev_appdeployment_spec.registry.name }} is not found in the namepsace {{ _cicd_kemo_dev_appdeployment_spec.registry.namespace }}"
        success_msg: "The specified Image Registry CR is found in the cluster - proceeding with the deployment"

  rescue:
    - name: Failed to find the Image Registry CR
      operator_sdk.util.k8s_status:
        api_version: cicd.kemo.dev/v1alpha1
        kind: AppDeployment
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        conditions:
        - type: ImageRegistryAvailable
          status: "False"
          reason: ImageRegistryNotFound
          message: "The specified Image Registry CR with the name {{ _cicd_kemo_dev_appdeployment_spec.registry.name }} is not found in the namepsace {{ _cicd_kemo_dev_appdeployment_spec.registry.namespace }}"
          lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"
    - ansible.builtin.fail:
        msg: "The specified Image Registry CR with the name {{ _cicd_kemo_dev_appdeployment_spec.registry.name }} is not found in the namepsace {{ _cicd_kemo_dev_appdeployment_spec.registry.namespace }}"

- name: Pass a successful status if the Image Registry CR is found
  operator_sdk.util.k8s_status:
    api_version: cicd.kemo.dev/v1alpha1
    kind: AppDeployment
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    conditions:
    - type: ImageRegistryAvailable
      status: "True"
      reason: ImageRegistryFound
      message: "The specified Image Registry CR with the name {{ _cicd_kemo_dev_appdeployment_spec.registry.name }} is found in the namepsace {{ _cicd_kemo_dev_appdeployment_spec.registry.namespace }}"
      lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"

- name: Check for the target GitRepo CR
  block:
    - name: Get the specified target GitRepo CR
      kubernetes.core.k8s_info:
        api_version: cicd.kemo.dev/v1alpha1
        kind: GitRepo
        name: "{{ _cicd_kemo_dev_appdeployment_spec.target.gitRepo.name }}"
        namespace: "{{ _cicd_kemo_dev_appdeployment_spec.target.gitRepo.namespace }}"
      register: target_gitrepo_info

    - name: Fail if the target GitRepo CR is not found
      ansible.builtin.assert:
        that:
          - target_gitrepo_info.resources | length > 0
        fail_msg: "The specified target GitRepo CR with the name {{ _cicd_kemo_dev_appdeployment_spec.target.gitRepo.name }} is not found in the namepsace {{ _cicd_kemo_dev_appdeployment_spec.target.gitRepo.namespace }}"
        success_msg: "The specified target GitRepo CR is found in the cluster - proceeding with the deployment"

  rescue:
    - name: Failed to find the target GitRepo CR
      operator_sdk.util.k8s_status:
        api_version: cicd.kemo.dev/v1alpha1
        kind: AppDeployment
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        conditions:
        - type: TargetGitRepoAvailable
          status: "False"
          reason: TargetGitRepoNotFound
          message: "The specified target GitRepo CR with the name {{ _cicd_kemo_dev_appdeployment_spec.target.gitRepo.name }} is not found in the namepsace {{ _cicd_kemo_dev_appdeployment_spec.target.gitRepo.namespace }}"
          lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"
    - ansible.builtin.fail:
        msg: "The specified target GitRepo CR with the name {{ _cicd_kemo_dev_appdeployment_spec.target.gitRepo.name }} is not found in the namepsace {{ _cicd_kemo_dev_appdeployment_spec.target.gitRepo.namespace }}"

- name: Pass a successful status if the target GitRepo CR is found
  operator_sdk.util.k8s_status:
    api_version: cicd.kemo.dev/v1alpha1
    kind: AppDeployment
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    conditions:
    - type: TargetGitRepoAvailable
      status: "True"
      reason: TargetGitRepoFound
      message: "The specified target GitRepo CR with the name {{ _cicd_kemo_dev_appdeployment_spec.target.gitRepo.name }} is found in the namepsace {{ _cicd_kemo_dev_appdeployment_spec.target.gitRepo.namespace }}"
      lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"