---
# defaults file for CICDSystem
pipelines:
  deploy_openshift_pipelines: true
  openshift_pipelines_channel: stable
  create_templates: true

cd:
  rhacm:
    enabled: true
    deploy_operator: true
    rhacm_operator_channel: release-2.10
    operator_update_strategy: Automatic # Automatic or Manual
    enable_observability: true
  argocd:
    enabled: true
    deploy_operator: true
    gitops_operator_channel: latest
    operator_update_strategy: Automatic # Automatic or Manual
  system_type: argocd # argocd or rhacm - this defines what kind of Application artifacts are created