---
# defaults file for CICDSystem
pipelines:
  deploy_openshift_pipelines: true
  openshift_pipelines_channel: stable

cd:
  deploy_operator: true
  system_type: argocd # argocd or rhacm
  gitops_operator_channel: latest