---
# defaults file for CICDSystem
pipelines:
  deploy_openshift_pipelines: true
  openshift_pipelines_channel: stable
  create_templates: true

cd:
  system_type: argocd # argocd or rhacm
  deploy_system_operator: true