{% if _cicd_kemo_dev_appdeployment_spec.registry.imageName is defined %}
{% set imageName = _cicd_kemo_dev_appdeployment_spec.registry.imageName %}
{% else %}
{% set imageName = _cicd_kemo_dev_appdeployment.metadata.name %}
{% endif %}

{% if image_registry_secret_info.resources[0].data['.dockerconfigjson'] is defined %}
{% set repoTargetJSON = image_registry_secret_info.resources[0].data['.dockerconfigjson'] | b64decode %}
{% endif %}
{% if image_registry_secret_info.resources[0].data['.dockercfg'] is defined %}
{% set repoTargetJSON = image_registry_secret_info.resources[0].data['.dockercfg'] | b64decode %}
{% endif %}
{% set repoTarget = lookup('ansible.builtin.dict', (repoTargetJSON | from_json).auths).key %}

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/instance: {{ _cicd_kemo_dev_appdeployment.metadata.name }}
    app.kubernetes.io/name: {{ _cicd_kemo_dev_appdeployment.metadata.name }}
    pipeline.openshift.io/strategy: docker
    pipeline.openshift.io/type: kubernetes
  name: {{ _cicd_kemo_dev_appdeployment.metadata.name }}
  namespace: {{ ansible_operator_meta.namespace }}
spec:
  params:
    - default: {{ _cicd_kemo_dev_appdeployment.metadata.name }}
      name: APP_NAME
      type: string
    - default: '{{ source_gitrepo_info.resources[0].spec.url }}'
      name: GIT_REPO
      type: string
    - default: '{{ source_gitrepo_info.resources.spec.branch }}'
      name: GIT_REVISION
      type: string
    - default: '{{ repoTarget }}/{{ _cicd_kemo_dev_appdeployment_spec.registry.path }}/{{ imageName }}'
      name: IMAGE_NAME
      type: string
    - default: {{ _cicd_kemo_dev_appdeployment_spec.sourceRepository.contextDir }}
      name: PATH_CONTEXT
      type: string
    - name: DOCKERFILE
      default: {{ _cicd_kemo_dev_appdeployment_spec.build.dockerfile }}
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        #name: buildah
        name: buildah-multi-tag
      workspaces:
        - name: source
          workspace: workspace
        - name: dockerconfig
          workspace: dockerconfig
#    - name: deploy
#      params:
#        - name: SCRIPT
#          value: oc rollout status deploy/$(params.APP_NAME)
#      runAfter:
#        - build
#      taskRef:
#        kind: ClusterTask
#        name: openshift-client
  workspaces:
    - name: workspace
    - name: dockerconfig
      optional: true
    - name: target
      optional: true
